In [ ]:
import pandas as pd
import numpy as np
df= pd.read_csv("/home/train.csv")

In [ ]:
df = df[["sobreviveu",
         "classe_social",
         "sexo",
         "idade",
         "parentes",
         "dependentes",
         "tarifa",
         "cabine",
         "embarque"]]
df.head(50)

sobreviveu  classe_social    sexo  idade  parentes  dependentes    tarifa  \
0            0              3    male   22.0         1            0    7.2500   
1            1              1  female   38.0         1            0   71.2833   
2            1              3  female   26.0         0            0    7.9250   
3            1              1  female   35.0         1            0   53.1000   
4            0              3    male   35.0         0            0    8.0500   
5            0              3    male    NaN         0            0    8.4583   
6            0              1    male   54.0         0            0   51.8625   
7            0              3    male    2.0         3            1   21.0750   
8            1              3  female   27.0         0            2   11.1333   
9            1              2  female   14.0         1            0   30.0708   
10           1              3  female    4.0         1            1   16.7000   
11           1              1  female   58.0         0            0   26.5500   
12           0              3    male   20.0         0            0    8.0500   
13           0              3    male   39.0         1            5   31.2750   
14           0              3  female   14.0         0            0    7.8542   
15           1              2  female   55.0         0            0   16.0000   
16           0              3    male    2.0         4            1   29.1250   
17           1              2    male    NaN         0            0   13.0000   
18           0              3  female   31.0         1            0   18.0000   
19           1              3  female    NaN         0            0    7.2250   
20           0              2    male   35.0         0            0   26.0000   
21           1              2    male   34.0         0            0   13.0000   
22           1              3  female   15.0         0            0    8.0292   
23           1              1    male   28.0         0            0   35.5000   
24           0              3  female    8.0         3            1   21.0750   
25           1              3  female   38.0         1            5   31.3875   
26           0              3    male    NaN         0            0    7.2250   
27           0              1    male   19.0         3            2  263.0000   
28           1              3  female    NaN         0            0    7.8792   
29           0              3    male    NaN         0            0    7.8958   
30           0              1    male   40.0         0            0   27.7208   
31           1              1  female    NaN         1            0  146.5208   
32           1              3  female    NaN         0            0    7.7500   
33           0              2    male   66.0         0            0   10.5000   
34           0              1    male   28.0         1            0   82.1708   
35           0              1    male   42.0         1            0   52.0000   
36           1              3    male    NaN         0            0    7.2292   
37           0              3    male   21.0         0            0    8.0500   
38           0              3  female   18.0         2            0   18.0000   
39           1              3  female   14.0         1            0   11.2417   
40           0              3  female   40.0         1            0    9.4750   
41           0              2  female   27.0         1            0   21.0000   
42           0              3    male    NaN         0            0    7.8958   
43           1              2  female    3.0         1            2   41.5792   
44           1              3  female   19.0         0            0    7.8792   
45           0              3    male    NaN         0            0    8.0500   
46           0              3    male    NaN         1            0   15.5000   
47           1              3  female    NaN         0            0    7.7500   
48           0              3    ma

In [ ]:
labels = df.sobreviveu
labels.head(10)

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: sobreviveu, dtype: int64

In [ ]:
#localiza todas as linhas cujo valores não são numeros na coluna classe_social e imprime a tupla que mostra a dimensão
df.loc[pd.isna(df['classe_social']), 'classe_social'].shape

(0,)

In [ ]:
indefinidos_idade= df.loc[pd.isna(df['idade']), 'idade'].shape[0]
total = df.idade.shape[0]
print("Total: ", total)
print((indefinidos_idade/total)*100)

Total:  891
19.865319865319865


In [ ]:
def calcula_percentual_indefinido(dataframe, coluna): 
  indefinidos= dataframe.loc[pd.isna(dataframe[coluna]), coluna].shape[0]
  total = df.idade.shape[0]

  return((indefinidos_idade/total)*100)

In [ ]:
df = df.drop('cabine', axis=1)
#caso o drop fosse de mais colunas df=df.drop(colums=['cabine', idade])
df.head(10)

sobreviveu  classe_social    sexo  idade  parentes  dependentes   tarifa  \
0           0              3    male   22.0         1            0   7.2500   
1           1              1  female   38.0         1            0  71.2833   
2           1              3  female   26.0         0            0   7.9250   
3           1              1  female   35.0         1            0  53.1000   
4           0              3    male   35.0         0            0   8.0500   
5           0              3    male    NaN         0            0   8.4583   
6           0              1    male   54.0         0            0  51.8625   
7           0              3    male    2.0         3            1  21.0750   
8           1              3  female   27.0         0            2  11.1333   
9           1              2  female   14.0         1            0  30.0708   

  embarque  
0        S  
1        C  
2        S  
3        S  
4        S  
5        Q  
6        S  
7        S  
8        S  
9        C

In [ ]:
df = df[np.isfinite(df['idade'])]
df.head(50)

sobreviveu  classe_social    sexo  idade  parentes  dependentes    tarifa  \
0            0              3    male   22.0         1            0    7.2500   
1            1              1  female   38.0         1            0   71.2833   
2            1              3  female   26.0         0            0    7.9250   
3            1              1  female   35.0         1            0   53.1000   
4            0              3    male   35.0         0            0    8.0500   
6            0              1    male   54.0         0            0   51.8625   
7            0              3    male    2.0         3            1   21.0750   
8            1              3  female   27.0         0            2   11.1333   
9            1              2  female   14.0         1            0   30.0708   
10           1              3  female    4.0         1            1   16.7000   
11           1              1  female   58.0         0            0   26.5500   
12           0              3    male   20.0         0            0    8.0500   
13           0              3    male   39.0         1            5   31.2750   
14           0              3  female   14.0         0            0    7.8542   
15           1              2  female   55.0         0            0   16.0000   
16           0              3    male    2.0         4            1   29.1250   
18           0              3  female   31.0         1            0   18.0000   
20           0              2    male   35.0         0            0   26.0000   
21           1              2    male   34.0         0            0   13.0000   
22           1              3  female   15.0         0            0    8.0292   
23           1              1    male   28.0         0            0   35.5000   
24           0              3  female    8.0         3            1   21.0750   
25           1              3  female   38.0         1            5   31.3875   
27           0              1    male   19.0         3            2  263.0000   
30           0              1    male   40.0         0            0   27.7208   
33           0              2    male   66.0         0            0   10.5000   
34           0              1    male   28.0         1            0   82.1708   
35           0              1    male   42.0         1            0   52.0000   
37           0              3    male   21.0         0            0    8.0500   
38           0              3  female   18.0         2            0   18.0000   
39           1              3  female   14.0         1            0   11.2417   
40           0              3  female   40.0         1            0    9.4750   
41           0              2  female   27.0         1            0   21.0000   
43           1              2  female    3.0         1            2   41.5792   
44           1              3  female   19.0         0            0    7.8792   
49           0              3  female   18.0         1            0   17.8000   
50           0              3    male    7.0         4            1   39.6875   
51           0              3    male   21.0         0            0    7.8000   
52           1              1  female   49.0         1            0   76.7292   
53           1              2  female   29.0         1            0   26.0000   
54           0              1    male   65.0         0            1   61.9792   
56           1              2  female   21.0         0            0   10.5000   
57           0              3    male   28.5         0            0    7.2292   
58           1              2  female    5.0         1            2   27.7500   
59           0              3    male   11.0         5            2   46.9000   
60           0              3    male   22.0         0            0    7.2292   
61           1              1  female   38.0         0            0   80.0000   
62           0              1    male   45.0         1            0   83.4750   
63           0              3    ma

In [ ]:
calcula_percentual_indefinido(df, 'idade')

24.789915966386555

In [ ]:
df = df[ ~pd.isna(df.embarque)]
calcula_percentual_indefinido(df, 'embarque')

24.859550561797754

In [ ]:
df.classe_social.unique()

array([3, 1, 2])

In [ ]:
lista = [3, 4, 4, 5, 5, 6, 3, 6, 6, 4, 5]
set(lista)

{3, 4, 5, 6}

In [ ]:
def one_hot(categorias, valor):
  categorias = list(set(categorias))
  indice = categorias.index(valor)
  vetor = np.zeros(len(categorias))
  vetor[indice] = 1

  return vetor

In [ ]:
one_hot(df.classe_social, 1)

array([1., 0., 0.])

In [ ]:
one_hot(df.classe_social, 2)

array([0., 1., 0.])

In [ ]:
one_hot(df.classe_social, 3)

array([0., 0., 1.])

In [ ]:
df.classe_social = [  one_hot(df.classe_social, _) for _ in df.classe_social  ]

In [ ]:
df.head(10)

sobreviveu    classe_social    sexo  idade  parentes  dependentes  \
0            0  [0.0, 0.0, 1.0]    male   22.0         1            0   
1            1  [1.0, 0.0, 0.0]  female   38.0         1            0   
2            1  [0.0, 0.0, 1.0]  female   26.0         0            0   
3            1  [1.0, 0.0, 0.0]  female   35.0         1            0   
4            0  [0.0, 0.0, 1.0]    male   35.0         0            0   
6            0  [1.0, 0.0, 0.0]    male   54.0         0            0   
7            0  [0.0, 0.0, 1.0]    male    2.0         3            1   
8            1  [0.0, 0.0, 1.0]  female   27.0         0            2   
9            1  [0.0, 1.0, 0.0]  female   14.0         1            0   
10           1  [0.0, 0.0, 1.0]  female    4.0         1            1   

     tarifa embarque  
0    7.2500        S  
1   71.2833        C  
2    7.9250        S  
3   53.1000        S  
4    8.0500        S  
6   51.8625        S  
7   21.0750        S  
8   11.1333        S  
9   30.0708        C  
10  16.7000        S

In [ ]:
df.sexo = [one_hot(df.sexo, _) for _ in df.sexo]

In [ ]:
df.head()

sobreviveu    classe_social        sexo  idade  parentes  dependentes  \
0           0  [0.0, 0.0, 1.0]  [1.0, 0.0]   22.0         1            0   
1           1  [1.0, 0.0, 0.0]  [0.0, 1.0]   38.0         1            0   
2           1  [0.0, 0.0, 1.0]  [0.0, 1.0]   26.0         0            0   
3           1  [1.0, 0.0, 0.0]  [0.0, 1.0]   35.0         1            0   
4           0  [0.0, 0.0, 1.0]  [1.0, 0.0]   35.0         0            0   

    tarifa embarque  
0   7.2500        S  
1  71.2833        C  
2   7.9250        S  
3  53.1000        S  
4   8.0500        S

In [ ]:
df.embarque = [one_hot(df.embarque, _) for _ in df.embarque]

In [ ]:
df.head()

sobreviveu    classe_social        sexo  idade  parentes  dependentes  \
0           0  [0.0, 0.0, 1.0]  [1.0, 0.0]   22.0         1            0   
1           1  [1.0, 0.0, 0.0]  [0.0, 1.0]   38.0         1            0   
2           1  [0.0, 0.0, 1.0]  [0.0, 1.0]   26.0         0            0   
3           1  [1.0, 0.0, 0.0]  [0.0, 1.0]   35.0         1            0   
4           0  [0.0, 0.0, 1.0]  [1.0, 0.0]   35.0         0            0   

    tarifa         embarque  
0   7.2500  [1.0, 0.0, 0.0]  
1  71.2833  [0.0, 0.0, 1.0]  
2   7.9250  [1.0, 0.0, 0.0]  
3  53.1000  [1.0, 0.0, 0.0]  
4   8.0500  [1.0, 0.0, 0.0]

In [ ]:
df.sobreviveu = [one_hot(df.sobreviveu, _) for _ in df.sobreviveu]
df.head(10)

sobreviveu    classe_social        sexo  idade  parentes  dependentes  \
0   [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]   22.0         1            0   
1   [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]   38.0         1            0   
2   [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]   26.0         0            0   
3   [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]   35.0         1            0   
4   [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]   35.0         0            0   
6   [1.0, 0.0]  [1.0, 0.0, 0.0]  [1.0, 0.0]   54.0         0            0   
7   [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]    2.0         3            1   
8   [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]   27.0         0            2   
9   [0.0, 1.0]  [0.0, 1.0, 0.0]  [0.0, 1.0]   14.0         1            0   
10  [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]    4.0         1            1   

     tarifa         embarque  
0    7.2500  [1.0, 0.0, 0.0]  
1   71.2833  [0.0, 0.0, 1.0]  
2    7.9250  [1.0, 0.0, 0.0]  
3   53.1000  [1.0, 0.0, 0.0]  
4    8.0500  [1.0, 0.0, 0.0]  
6   51.8625  [1.0, 0.0, 0.0]  
7   21.0750  [1.0, 0.0, 0.0]  
8   11.1333  [1.0, 0.0, 0.0]  
9   30.0708  [0.0, 0.0, 1.0]  
10  16.7000  [1.0, 0.0, 0.0]

In [ ]:
def normaliza_min(valores):
  # media = np.mean(valores)
  minimo = np.min(valores)
  maximo = np.max(valores)
  return (valores - minimo)/(maximo-minimo)

In [ ]:
df.idade = normaliza_min(df.idade)
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.271174         1            0   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.472229         1            0   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.321438         0            0   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.434531         1            0   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.434531         0            0   

    tarifa         embarque  
0   7.2500  [1.0, 0.0, 0.0]  
1  71.2833  [0.0, 0.0, 1.0]  
2   7.9250  [1.0, 0.0, 0.0]  
3  53.1000  [1.0, 0.0, 0.0]  
4   8.0500  [1.0, 0.0, 0.0]

In [ ]:
df.dependentes = normaliza_min(df.dependentes)
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.271174         1          0.0   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.472229         1          0.0   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.321438         0          0.0   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.434531         1          0.0   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.434531         0          0.0   

    tarifa         embarque  
0   7.2500  [1.0, 0.0, 0.0]  
1  71.2833  [0.0, 0.0, 1.0]  
2   7.9250  [1.0, 0.0, 0.0]  
3  53.1000  [1.0, 0.0, 0.0]  
4   8.0500  [1.0, 0.0, 0.0]

In [ ]:
df.tarifa = normaliza_min(df.tarifa)
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.271174         1          0.0   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.472229         1          0.0   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.321438         0          0.0   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.434531         1          0.0   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.434531         0          0.0   

     tarifa         embarque  
0  0.014151  [1.0, 0.0, 0.0]  
1  0.139136  [0.0, 0.0, 1.0]  
2  0.015469  [1.0, 0.0, 0.0]  
3  0.103644  [1.0, 0.0, 0.0]  
4  0.015713  [1.0, 0.0, 0.0]

In [ ]:
df.parentes = normaliza_min(df.parentes)
df.head()

sobreviveu    classe_social        sexo     idade  parentes  dependentes  \
0  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.271174       0.2          0.0   
1  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.472229       0.2          0.0   
2  [0.0, 1.0]  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.321438       0.0          0.0   
3  [0.0, 1.0]  [1.0, 0.0, 0.0]  [0.0, 1.0]  0.434531       0.2          0.0   
4  [1.0, 0.0]  [0.0, 0.0, 1.0]  [1.0, 0.0]  0.434531       0.0          0.0   

     tarifa         embarque  
0  0.014151  [1.0, 0.0, 0.0]  
1  0.139136  [0.0, 0.0, 1.0]  
2  0.015469  [1.0, 0.0, 0.0]  
3  0.103644  [1.0, 0.0, 0.0]  
4  0.015713  [1.0, 0.0, 0.0]

In [ ]:
labels = df.sobreviveu.values

In [ ]:
df = df.drop(['sobreviveu'], axis=1)
df.head(10)

classe_social        sexo     idade  parentes  dependentes    tarifa  \
0   [0.0, 0.0, 1.0]  [1.0, 0.0]  0.271174       0.2     0.000000  0.014151   
1   [1.0, 0.0, 0.0]  [0.0, 1.0]  0.472229       0.2     0.000000  0.139136   
2   [0.0, 0.0, 1.0]  [0.0, 1.0]  0.321438       0.0     0.000000  0.015469   
3   [1.0, 0.0, 0.0]  [0.0, 1.0]  0.434531       0.2     0.000000  0.103644   
4   [0.0, 0.0, 1.0]  [1.0, 0.0]  0.434531       0.0     0.000000  0.015713   
6   [1.0, 0.0, 0.0]  [1.0, 0.0]  0.673285       0.0     0.000000  0.101229   
7   [0.0, 0.0, 1.0]  [1.0, 0.0]  0.019854       0.6     0.166667  0.041136   
8   [0.0, 0.0, 1.0]  [0.0, 1.0]  0.334004       0.0     0.333333  0.021731   
9   [0.0, 1.0, 0.0]  [0.0, 1.0]  0.170646       0.2     0.000000  0.058694   
10  [0.0, 0.0, 1.0]  [0.0, 1.0]  0.044986       0.2     0.166667  0.032596   

           embarque  
0   [1.0, 0.0, 0.0]  
1   [0.0, 0.0, 1.0]  
2   [1.0, 0.0, 0.0]  
3   [1.0, 0.0, 0.0]  
4   [1.0, 0.0, 0.0]  
6   [1.0, 0.0, 0.0]  
7   [1.0, 0.0, 0.0]  
8   [1.0, 0.0, 0.0]  
9   [0.0, 0.0, 1.0]  
10  [1.0, 0.0, 0.0]

In [ ]:
def vetorizar(classe_social, sexo, idade, parentes, dependentes, tarifa, embarque):
    return classe_social.tolist() + sexo.tolist() + [idade] + [parentes] + [dependentes] + [tarifa] + embarque.tolist()

In [ ]:
entrada = [vetorizar(*_) for _ in df.values]
entrada

[[0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.2711736617240513,
  0.2,
  0.0,
  0.014151057562208049,
  1.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.4722292033174164,
  0.2,
  0.0,
  0.13913573538264068,
  0.0,
  0.0,
  1.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.32143754712239253,
  0.0,
  0.0,
  0.015468569817999833,
  1.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.43453128926866047,
  0.2,
  0.0,
  0.10364429745562033,
  1.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.43453128926866047,
  0.0,
  0.0,
  0.015712553569072387,
  1.0,
  0.0,
  0.0],
 [1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.6732847449107816,
  0.0,
  0.0,
  0.10122885832000206,
  1.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.01985423473234481,
  0.6,
  0.16666666666666666,
  0.04113566043083236,
  1.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.33400351847197784,
  0.0,
  0.3333333333333333,
  0.021730754366528396,
  1.0,
  0.0,
  0.0],
 [0.0,
  1.0,
  0.0,
  0.0,
  1.

In [ ]:
#model.predict()

cores = ['preto', 'preto', 'azul', 'vermelho', 'azul', 'rosa']

#Aplicando label_encoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
valores_numericos = label_encoder.fit_transform(cores)
print(valores_numericos)

[1 1 0 3 0 2]


In [ ]:
#One Hot Encoding
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False) #sparse=False gera matriz de vetores

#transforma a lista de valores em uma lista de 1 dimensão
inteiros = valores_numericos.reshape(len(valores_numericos),1)
#inteiros

In [ ]:
#Passa os valores para o objeto onehot_encoder fazer a transformação.
vetores_binarios = onehot_encoder.fit_transform(inteiros)
print(cores)
print("_______________________________________________")
print(vetores_binarios)

['preto', 'preto', 'azul', 'vermelho', 'azul', 'rosa']
_______________________________________________
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
